from building import *

cwd = GetCurrentDir()

src  = Glob('*.c')

#if GetDepend('RT_USING_ADC') == False:
#   SrcRemove(src, 'adc_test.c')

group = DefineGroup('test', src, depend = [''])

Return('group')

